name: .NET build and test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    build-and-test:
        uses: The-Poolz/.net-workflows/.github/workflows/build-and-test.yml@v1.0.6
